fix istio-policy that istio-proxy sidecar depending on global.control…
istio/installer pull request #330
Opened 2019-08-14 08:07 UTC by waret

…PlaneSecurityEnabled

2019-08-30 21:03 UTC, costinm approved these changes

2019-10-01 20:22 UTC, istio-testing commented
@waret: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_installer | 432e645208a62f1fde2f382cecbebb80d89dc714 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_installer/330/build_installer/121) | `/test build_installer`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-10-01 20:22 UTC, istio-testing commented
@waret: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lintmodern_installer | 432e645208a62f1fde2f382cecbebb80d89dc714 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_installer/330/lintmodern_installer/99) | `/test lintmodern_installer`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-10-20 16:03 UTC, howardjohn requested changes

2019-10-20 16:03 UTC, howardjohn commented on global.yaml
> +  telemetryNamespace: istio-telemetry
We are not installing in separate namespace anymore

2019-10-25 19:06 UTC, istio-testing commented
@waret: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_installer | 432e645208a62f1fde2f382cecbebb80d89dc714 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_installer/330/build_installer/121) | `/test build_installer`
lintmodern_installer | 432e645208a62f1fde2f382cecbebb80d89dc714 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_installer/330/lintmodern_installer/99) | `/test lintmodern_installer`
lint_installer | 432e645208a62f1fde2f382cecbebb80d89dc714 | [link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_installer/330/lint_installer/7) | `/test lint_installer`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2019-11-06 07:03 UTC, closed without merging